[package]
name = "cr8t"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = { version = "2.1", features = ["chrono"] }
diesel-async = { version = "0.4", features = ["postgres"] }
chrono = "0.4"
